"""empty message

Revision ID: 28bce0c1bb90
Revises: None
Create Date: 2015-01-31 21:11:52.974446

"""

# revision identifiers, used by Alembic.
revision = '28bce0c1bb90'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
