"""empty message

Revision ID: 412a7c53a861
Revises: aafdadaa42b
Create Date: 2015-02-02 10:35:34.243877

"""

# revision identifiers, used by Alembic.
revision = '412a7c53a861'
down_revision = 'aafdadaa42b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
